# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7c4c8d61c577aecb955abd1733a9b09fb3d596fa088c3fe991579602c8937c3f8d1e26ed44827c988b0126869f3ebd077569bb8cc3e40c015567daf9bc26b6c

test:
  secret_key_base: a403087f32a276543349d6cfe41265540c9d8a83e3d27217bbbb25d02c40a5bf6af0207b123eb0f60413f7bfb48a485608b6970e83808b81c7839b4060428fed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
